print(".............................")
print(".         ppppppppp         .")
print(".      pp           pp      .")
print(".     pp             pp     .")
print(".    pp    pp   pp    pp    .")
print(".   pp     pp   pp     pp   .")
print(".   pp                 pp   .")
print(".   pp  pp         pp  pp   .")
print(".    pp   pp      pp  pp    .")
print(".     pp    pppppp   pp     .")
print(".      pp           pp      .")
print(".         ppppppppp         .")
print(".............................")
